
export PS1='\033[32m\u@\h\033[00m \033[1m\w\033[0m\n\$ '

export HISTCONTROL=ignorespace,erasedups
export HISTFILESIZE=150000
export HISTSIZE=50000

export PATH=$HOME/bin:$PATH

export ACK_COLOR_MATCH=red
alias h="ack --passthru"

if [ -f "$HOME/.bashrc_local" ]; then
  source "$HOME/.bashrc_local"
fi
